version: '2'
services:
    speakers:
        container_name: speakers
        build:
            context: .
            dockerfile: Dockerfile
        image: noamgrinch/speakersservice:latest
        expose:
            - 8089
        networks:
            - mysql-network
            - broker-network
            - grpc-network
        ports:
            - 8089:8089
            - 9099:9099
networks:
  mysql-network:
    external:
      name: mysql-network
  broker-network:
    external:
      name: broker-network
  grpc-network:
    external:
      name: grpc-network