version: '2'
services:
    manufacturers:
        container_name: manufacturers
        build:
            context: .
            dockerfile: Dockerfile
        image: noamgrinch/manufacturersservice:latest
        expose:
            - 8090
        networks:
            - mysql-network
            - broker-network
            - grpc-network
        ports:
            - 8090:8090
            - 9090:9090
networks:
  mysql-network:
    external:
      name: mysql-network
  broker-network:
    external:
      name: broker-network
  grpc-network:
    external:
      name: grpc-network